### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by probablyanxious**

### CODE REVIEW

**Comment by LukeGostlin** [comment]
[Luke G HIST 4805 09_30.txt](https://github.com/user-attachments/files/17805023/Luke.G.HIST.4805.09_30.txt)

[HIST4805 07_10.txt](https://github.com/user-attachments/files/17805040/HIST4805.07_10.txt)

[HIST4805 10_28.txt](https://github.com/user-attachments/files/17805055/HIST4805.10_28.txt)

[HIST 4805 11_11.txt](https://github.com/user-attachments/files/17805063/HIST.4805.11_11.txt)

[HIST4805 11_18.txt](https://github.com/user-attachments/files/17805071/HIST4805.11_18.txt)

**Comment by shawngraham** [comment]
markdown files would be prefered! (save-as and use the .md extension)

**Comment by LukeGostlin** [comment]
I can revise and resend the files as .md if that helps!

**Comment by LukeGostlin** [comment]
[HIST4805 11_25.md](https://github.com/user-attachments/files/17907639/HIST4805.11_25.md)

**Comment by shawngraham** [comment]
no worries.

**Pull request merged**
